description: "A new cross-platform email client."
name: "enbox"
version: "1.0.0+1"
dependencies:
  cupertino_icons: "^0.1.2"
  flutter:
    sdk: flutter
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  # Necessary as a supplement to the builtin icons.
  material_design_icons_flutter: 4.0.5145
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.7.0 <3.0.0"
flutter:
  uses-material-design: true