name: Check build pass/fail

on:
  pull_request:
    branches:
      - master

jobs:
  build-test-web:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        # Checks out your repository under $GITHUB_WORKSPACE so the job can access it
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up the Flutter build
        uses: subosito/flutter-action@v1.2.0
        with:
          channel: beta
      - name: Enable Flutter web
        run: flutter config --enable-web
      - name: Upgrade Flutter and build binaries
        run: |
          flutter upgrade
          flutter packages get
          flutter build web --release
      - name: Save artifact to display build pass/fail
        uses: actions/upload-artifact@v1
        with:
          name: bin-web
          path: build

  build-test-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set OS to Windows
        if: runner.os == 'Windows'
        run: echo ::set-env name=OS::windows
        # Required since default shell on Windows is pwsh
        shell: bash
      - name: Set OS to macOS (and set release flag)
        if: runner.os == 'macOS'
        run: |
          echo ::set-env name=OS::macos
          echo ::set-env name=FLAGS::--release
      - name: Set OS to Linux
        if: runner.os == 'Linux'
        run: echo ::set-env name=OS::linux
      - name: Check out repository
        # Checks out your repository under $GITHUB_WORKSPACE so the job can access it
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up the Flutter build
        run: |
          git clone https://github.com/flutter/flutter.git
          echo ::set-env name=PATH::$PATH:$(pwd)/flutter/bin
        shell: bash
      - name: (Windows) Upgrade Flutter to detect platform
        if: runner.os == 'Windows'
        run: flutter/bin/flutter upgrade
        shell: powershell
      - name: Configure Flutter build binaries based on OS
        # Configures Flutter to build a binary on the platform it's running on
        run: flutter config --enable-$OS-desktop
        # Windows...
        shell: bash
      - name: Upgrade Flutter to master channel
        run: |
          flutter channel master
          flutter upgrade
      - name: Build binaries
        run: |
          flutter packages get
          flutter build $OS $FLAGS
        # Windows...
        shell: bash
      - name: Save artifact to display build pass/fail
        uses: actions/upload-artifact@v1
        with:
          name: bin-${{ env.OS }}
          path: build
